### PR TITLE
fix rect being off by one vertically

### PR DESCRIPTION
**Pull request by gingerbeardman**
see: api.p8 (from the bundled demos)

screen shot 2016-08-08 at 12 21 57

### CODE REVIEW

**Comment by gamax92** [comment]
Well this is fun. On all my devices here I get this:
LLVMPIPE

Seems to be some issue with whatever graphics device you have

**Comment by gamax92** [comment]
Test, what happens if you replace both those +1's with +0.5, I've been told that using +1 is wrong since the offset in OpenGL is actually a half pixel offset.

**Comment by gingerbeardman** [comment]
Aha! Now this brings back a memory:

https://github.com/picolove/picolove/issues/1

My initial hunch, when I filed the issue directly above this sentence, was that I was working on a Retina MBP. But the issue I filed to you, that this thread is about, was witnessed on my non-retina iMac.

Will test my iMac and get back to you.

Ps: your original code works fine, everything is aligned, on my Retina MBP.

**Comment by gingerbeardman** [comment]
OK, as you can see using 0.5 fixes things on my iMac (AMD Radeon HD 6750M 512 MB)

Good news!

**Comment by gamax92** [comment]
Yeah, when I did a little bit of testing, I had found out using 1 is very wrong and questionable why it even works. It's about 0.001 off from getting junked down onto another line. Thank you for the testing!

**Pull request merged**
