### PR TITLE
Bugfixes for gamax92 fork

### PR DESCRIPTION
**Pull request by samhocevar**

### CODE REVIEW

**Comment by josefnpat** [comment]
I feel like instead of having two forks of picolove, we could just merge @gamax92 's features in and allow folks to enable them. Food for thought I suppose

**Comment by gamax92** [comment]
@josefnpat I'd love to do that but Shoozza has not gotten back to me.

**Comment by gamax92** [comment]
Changes LGTM. Thanks for the PR

**Comment by gamax92** [comment]
I'm not tired.

**Comment by josefnpat** [comment]
lol, any way we can ping Shoozza? Don't know his/her handle.

**Pull request merged**
